Repository AY2425S1-CS2103T-T08-3/tp, pull requests merged in 2024-10, with the labels that each got.

#22 Add axel's photo
  docs/images/shinichi04.png
Labels: type.Task

#23 Add photo to images directory
  docs/images/sandyk0105.png
Labels: type.Task

#21 Branch add photo
  docs/images/tyxiangs.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#32 Update AboutUs for Sandy
  docs/AboutUs.md
Labels: type.Task

#30 Update AboutUs.md for Nigel
  docs/AboutUs.md
Labels: type.Task

#29 Edit AboutUs for Axel
  docs/AboutUs.md
Labels: type.Task

#31 Update AboutUs page for course admin purposes
  docs/AboutUs.md
Labels: type.Task

#38 Update Ui.png and index.md
  docs/images/Ui.png
  docs/index.md
Labels: type.Task

#39 Update website
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/nigeltzy.png
  docs/index.md
Labels: type.Task

#45 Update project website
  docs/_config.yml
Labels: type.Enhancement

#46 Modify Project Title
  docs/_sass/minima/_base.scss
  docs/index.md
Labels: type.Enhancement

#48 Branch add doctor
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/History.java
Labels: type.Task

#49 Project website
  docs/DeveloperGuide.md
Labels: type.Enhancement

#51 Add a History class
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/person/History.java
Labels: type.Task

#66 Add toString functionality and update generics for Appointment.java
  src/main/java/seedu/address/model/person/Appointment.java
Labels: type.Task

#69 Add deleteAppointment Command
  src/main/java/seedu/address/commons/exceptions/InvalidIdException.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium, type.feature

#65 History class: refactor appointment handling and formatting
  src/main/java/seedu/address/model/person/History.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#75 Branch view history
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/person/History.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#80 CheckAppointmentCommand: add new command for appointment checks
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/History.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#81 Add command and parser for delete patient.
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/DeletePatientCommandParser.java
  src/main/java/seedu/address/model/person/History.java
Labels: type.feature

#82 76 add test coverage apt patient doctor
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Pair.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/DoctorTest.java
  src/test/java/seedu/address/model/person/PatientTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#93 Modify the Person class logic
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/CreatePatientCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/DoctorTest.java
  src/test/java/seedu/address/model/person/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement

#114 Branch check appointment command modification
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#109 Add test for CreateDoctorCommand execution success
  src/test/java/seedu/address/logic/commands/CreateDoctorCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.Medium

#116 Add MarkAppointmentCommand and Parser.
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkAppointmentCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Appointmentable.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.feature

#111 CreatePatientCommandTest: Add tests for patient creation
  src/test/java/seedu/address/logic/commands/CreatePatientCommandTest.java
Labels: type.Task

#123 Fix MarkAppointmentCommand
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/model/person/Appointmentable.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.High

#117 Branch check appointment command test
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CheckAppointmentCommandTest.java
Labels: type.Task

#113 Add tests for DeletePatientCommand
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/DeletePatientCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Id.java
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNotesCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Test

#126 Modify Existing Architecture Sequence Diagram
  build.gradle
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation

#128 Update ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation

#132 UML Modification
  docs/DeveloperGuide.md
  docs/diagrams/CreateDoctorCommand-Logic.puml
  docs/diagrams/CreatePatientCommand-Logic.puml
  docs/images/CreateDoctorCommand-Logic.png
  docs/images/CreatePatientCommand-Logic.png
Labels: priority.Medium

#135 MarkAppointmentCommandTest: add unit test for marking appointments
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/test/java/seedu/address/logic/commands/MarkAppointmentCommandTest.java
Labels: type.Task

#137 RemarkCommandTest: add unit test for remark functionality
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task
