Repository AY2425S1-CS2103T-T08-3/tp, pull requests merged in 2024-11, with the labels that each got.

#141 Branch user guide update feature
  docs/UserGuide.md
Labels: type.Task

#143 Modify existing commands
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddRemarksCommand.java
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/CreateDoctorCommand.java
  src/main/java/seedu/address/logic/commands/CreatePatientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GetIdCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddRemarksCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRemarksCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#144 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddRemarksCommand.java
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
Labels: type.Task

#162 Fix EditPerson , AddRemarks, CreatePatient and CreateDoctor Commands
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddRemarksCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateDoctorCommand.java
  src/main/java/seedu/address/logic/commands/CreatePatientCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/GetIdCommand.java
  src/main/java/seedu/address/logic/parser/AddRemarksCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRemarksCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/CreatePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRemarksCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: alpha-bug

#171 Fix CreateP, CreateD and Delete Commands
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateDoctorCommand.java
  src/main/java/seedu/address/logic/commands/CreatePatientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: alpha-bug

#174 Branch alpha bug fix appointment
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Appointmentable.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CheckAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
Labels: type.Bug

#176 More test cases for parsers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GetIdCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CheckAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#196 Create Command Parser Tests for Person-related Commands
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/CreateDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreatePatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#215 Fix bugged formatting, include new tips
  docs/UserGuide.md
Labels: type.Documentation

#218 Fix quick start hyperlink
  docs/UserGuide.md
Labels: type.Bug

#315 Fix UG Bugs
  docs/UserGuide.md
  docs/images/clearMessage.png
  src/main/java/seedu/address/logic/commands/CreateDoctorCommand.java
  src/main/java/seedu/address/logic/commands/CreatePatientCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Documentation

#317 User Guide Bug Fixing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: UG-bug

#318 Fix typo
  docs/UserGuide.md
Labels: UG-bug

#320 Fix DG bugs
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: DG-bug

#322 PE Bug Fixing
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddRemarksCommand.java
  src/main/java/seedu/address/logic/commands/CheckAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/CreateDoctorCommand.java
  src/main/java/seedu/address/logic/commands/CreatePatientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/CreatePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CheckAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
Labels: type.Task

#329 Fix UG again
  docs/UserGuide.md
Labels: UG-bug
